[tool.black]
target-version = ["py37"]
line-length = 90
extend-exclude = '''
/(
  | venv
  | u8adapter
)/
'''

[tool.pycln]
all=true

[tool.isort]
line_length = 90
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = 3.7
plugins = "sqlmypy"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
# Needed because of bug in MyPy
disallow_subclassing_any = false
mypy_path = "stubs"


# [mypy-*]
# [tool.mypy.overrides]
# module = "app.*"
disallow_untyped_calls = false
disallow_untyped_defs = false
check_untyped_defs = true
no_implicit_optional = true
strict_optional = true
warn_unreachable = true
warn_return_any = true
